a = 3
b = 2
sum = a + b
diff = a - b
product = a * b
division = a / b
remainder = a % b
floor_division = a // b
exponential = a ** b
print(sum)
print("a + b:",sum)
print("a - b:",diff)
print("a * b", product)
print("a / b:", division)
print("a % b:", remainder)
print("a // b:", floor_division)
print("a ** b:", exponential)
print(3>2)
print(3>=2)
print(3<2)
print(2<3)
print(2<=3)
print(3==2)
print(3!=2)
print(len("mango")== len("avocado"))
print(len("mango")!= len("avocado"))
print(len("mango")< len("avocado"))
print(len("milk")!= len("meat"))
print(len("milk")==len("meat"))
print(len("tomato")== len("potato"))
print(len("python")>len("dragon"))
print("True == True: ", True == True)
print("True == false: ", True == False)
print("False == False: ", False == False)
print("1 is 1", 1 is 1)
print("1 is not 2", 1 is not 2)
print("a in Muhammed", "a" in "Muhammed")
print("b in alabi", "b" in "alabi")
print("coding in coding for all", "coding" in "coding for all")
print("a in an:", "a" in "an")
print("4 is 2 ** 2", 4 is 2 ** 2)
print("logical operators")
print(3>2 and 4<3)
print(3>2 and 4<3)
print(3<2 and 4<3)
print("True and True:", True and True)
print(3>2 or 4>3)
print(3>2 or 4>3)
print(3<2 or 4<3)
print("True or False:", True or False)
print(not 3>2)
print(not True)
print(not False)
print(not not True)
print(not not False)
