SELECT * FROM chicago_crime_data;
SELECT PRIMARY_TYPE FROM chicago_crime_data;
SELECT count(PRIMARY_TYPE) FROM chicago_crime_data;
SELECT count(DISTINCT PRIMARY_TYPE) as number_of_crime FROM chicago_crime_data;
SELECT COMMUNITY_AREA_NAME FROM census_data WHERE (PER_CAPITA_INCOME < 11000);
SELECT CASE_NUMBER FROM chicago_crime_data WHERE (PRIMARY_TYPE = "OFFENSE INVOLVING CHILDREN");
SELECT * FROM chicago_crime_data WHERE PRIMARY_TYPE = "KIDNAPPING";
UPDATE chicago_crime_data SET LOCATION_DESCRIPTION = REPLACE(LOCATION_DESCRIPTION, '"', '') WHERE LOCATION_DESCRIPTION LIKE '%"%';
SELECT PRIMARY_TYPE FROM chicago_crime_data WHERE LOCATION_DESCRIPTION = "SCHOOL";
SELECT avg(SAFETY_SCORE) as average_safety_score FROM chicago_public_schools;
SELECT * FROM census_data;
SELECT COMMUNITY_AREA_NAME, PERCENT_HOUSEHOLDS_BELOW_POVERTY FROM census_data ORDER BY PERCENT_HOUSEHOLDS_BELOW_POVERTY DESC LIMIT 5;
SELECT COMMUNITY_AREA_NUMBER, count(PRIMARY_TYPE) as number_of_crimes FROM chicago_crime_data GROUP BY PRIMARY_TYPE ORDER BY count(PRIMARY_TYPE) DESC;
SELECT COMMUNITY_AREA_NAME FROM census_data WHERE HARDSHIP_INDEX = (SELECT max(HARDSHIP_INDEX) FROM census_data);
SELECT COMMUNITY_AREA_NAME FROM census_data WHERE COMMUNITY_AREA_NUMBER IN (SELECT COMMUNITY_AREA_NUMBER FROM chicago_crime_data WHERE COMMUNITY_AREA_NUMBER = 58)